"""Generate small synthetic sample media for end-to-end plumbing tests.

These files are NOT real-world benchmark samples and are NOT useful for
evaluating detector quality/accuracy. They exist only to prove that the
upload -> inference -> response pipeline works for each media type and
endpoint.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import soundfile as sf
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
IMAGES_DIR = ROOT / "samples" / "images"
AUDIO_DIR = ROOT / "samples" / "audio"
VIDEOS_DIR = ROOT / "samples" / "videos"

IMAGE_PATH = IMAGES_DIR / "test_image.png"
AUDIO_PATH = AUDIO_DIR / "test_audio.wav"
VIDEO_PATH = VIDEOS_DIR / "test_video.mp4"

NOTE = (
    "NOTE: samples/ files are SYNTHETIC PLUMBING MEDIA generated by "
    "scripts/generate_sample_media.py. They prove endpoints and model "
    "plumbing work end-to-end. They are NOT real benchmark samples and are "
    "NOT useful for evaluating detector quality/accuracy."
)


def ffmpeg_path() -> str:
    exe = shutil.which("ffmpeg")
    if exe:
        return exe
    import imageio_ffmpeg

    return imageio_ffmpeg.get_ffmpeg_exe()


def generate_frame(size: tuple[int, int], frame_index: int) -> Image.Image:
    image = Image.new("RGB", size, color=(20, 20, 30))
    draw = ImageDraw.Draw(image)
    for y in range(size[1]):
        shade = int(255 * y / size[1])
        draw.line([(0, y), (size[0], y)], fill=(shade, 60, 255 - shade))
    offset = (frame_index * 14) % max(size[0] - 80, 1)
    draw.ellipse([offset, 40, offset + 80, 120], fill=(255, 220, 0))
    draw.rectangle([8, 8, 220, 34], fill=(0, 0, 0))
    draw.text((14, 12), f"TraceProofAI sample frame {frame_index:03d}", fill=(255, 255, 255))
    return image


def generate_image() -> None:
    IMAGES_DIR.mkdir(parents=True, exist_ok=True)
    generate_frame((320, 240), 0).save(IMAGE_PATH)
    print(f"Generated {IMAGE_PATH}")


def generate_audio(duration_s: float = 3.0, sample_rate: int = 16000) -> None:
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    t = np.linspace(0, duration_s, int(sample_rate * duration_s), endpoint=False)
    tone = 0.3 * np.sin(2 * np.pi * 220.0 * t) + 0.15 * np.sin(2 * np.pi * 440.0 * t)
    fade = min(0.05, duration_s / 2)
    envelope = np.clip(np.minimum(t / fade, (duration_s - t) / fade), 0.0, 1.0)
    waveform = (tone * envelope).astype(np.float32)
    sf.write(AUDIO_PATH, waveform, sample_rate)
    print(f"Generated {AUDIO_PATH}")


def generate_video(fps: int = 5, num_frames: int = 15) -> None:
    if not AUDIO_PATH.exists():
        generate_audio()

    VIDEOS_DIR.mkdir(parents=True, exist_ok=True)
    frames_dir = VIDEOS_DIR / "_frames_tmp"
    frames_dir.mkdir(parents=True, exist_ok=True)
    try:
        for i in range(num_frames):
            generate_frame((320, 240), i).save(frames_dir / f"frame-{i:03d}.png")

        cmd = [
            ffmpeg_path(),
            "-y",
            "-framerate",
            str(fps),
            "-i",
            str(frames_dir / "frame-%03d.png"),
            "-i",
            str(AUDIO_PATH),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
            str(VIDEO_PATH),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode != 0:
            raise RuntimeError(f"ffmpeg failed (exit {result.returncode}): {result.stderr.strip()[-2000:]}")
        print(f"Generated {VIDEO_PATH}")
    finally:
        shutil.rmtree(frames_dir, ignore_errors=True)


def main() -> None:
    created: list[str] = []

    if not IMAGE_PATH.exists():
        generate_image()
        created.append(str(IMAGE_PATH.relative_to(ROOT)))
    else:
        print(f"SKIP {IMAGE_PATH} already exists")

    if not AUDIO_PATH.exists():
        generate_audio()
        created.append(str(AUDIO_PATH.relative_to(ROOT)))
    else:
        print(f"SKIP {AUDIO_PATH} already exists")

    if not VIDEO_PATH.exists():
        try:
            generate_video()
            created.append(str(VIDEO_PATH.relative_to(ROOT)))
        except Exception as exc:
            print(f"FAILED to generate {VIDEO_PATH}: {exc}", file=sys.stderr)
    else:
        print(f"SKIP {VIDEO_PATH} already exists")

    print()
    print(NOTE)
    if created:
        print("Created:", ", ".join(created))


if __name__ == "__main__":
    main()
